#!/bin/zsh
cd "/run/media/SSD/SteamLibrary/steamapps/common/DynDOLOD/"
WINEPREFIX=/run/media/SSD/SteamLibrary/steamapps/compatdata/933480/pfx/  /home/kat/.local/share/Steam/compatibilitytools.d/proton_tkg_4.21.r8.g3a14d63a/dist/bin/wine "/run/media/SSD/SteamLibrary/steamapps/common/DynDOLOD/DynDOLODx64.exe" -enderal
