#!/bin/bash

cd ~/oblivion-git/Inventory-Alchemy/Item-Scripts/

# set up the variables
echo Enter desired effect type:
read EFFECT
# run the conditions for the right effect id
if [ $EFFECT = "Damage" ]; then
	CHAR=DGAT
elif [ $EFFECT = "Drain" ]; then
	CHAR=DRAT
elif [ $EFFECT = "Fortify" ]; then
	CHAR=FOAT
elif [ $EFFECT = "Restore" ]; then
	CHAR=REAT
fi

# these are our AV names
AGL=Agility
END=Endurance
STR=Strength
LCK=Luck
INT=Intelligence
SPD=Speed
WLP=Willpower
PRS=Personality

# cp the scripts from a master
cp IBAAbsorbAgility.obl "IBA$EFFECT$AGL.obl"
cp IBAAbsorbEndurance.obl "IBA$EFFECT$END.obl"
cp IBAAbsorbStrength.obl "IBA$EFFECT$STR.obl"
cp IBAAbsorbLuck.obl "IBA$EFFECT$LCK.obl"
cp IBAAbsorbIntelligence.obl "IBA$EFFECT$INT.obl"
cp IBAAbsorbSpeed.obl "IBA$EFFECT$SPD.obl"
cp IBAAbsorbWillpower.obl "IBA$EFFECT$WLP.obl"
cp IBAAbsorbPersonality.obl "IBA$EFFECT$PRS.obl"

# change effect IDs in the files
sed -i "s/ABAT/$CHAR/g" "IBA$EFFECT$AGL.obl"
sed -i "s/ABAT/$CHAR/g" "IBA$EFFECT$END.obl"
sed -i "s/ABAT/$CHAR/g" "IBA$EFFECT$STR.obl"
sed -i "s/ABAT/$CHAR/g" "IBA$EFFECT$LCK.obl"
sed -i "s/ABAT/$CHAR/g" "IBA$EFFECT$INT.obl"
sed -i "s/ABAT/$CHAR/g" "IBA$EFFECT$SPD.obl"
sed -i "s/ABAT/$CHAR/g" "IBA$EFFECT$WLP.obl"
sed -i "s/ABAT/$CHAR/g" "IBA$EFFECT$PRS.obl"

# change the effect name in the files
sed -i "s/Absorb/$EFFECT/g" "IBA$EFFECT$AGL.obl"
sed -i "s/Absorb/$EFFECT/g" "IBA$EFFECT$END.obl"
sed -i "s/Absorb/$EFFECT/g" "IBA$EFFECT$STR.obl"
sed -i "s/Absorb/$EFFECT/g" "IBA$EFFECT$LCK.obl"
sed -i "s/Absorb/$EFFECT/g" "IBA$EFFECT$INT.obl"
sed -i "s/Absorb/$EFFECT/g" "IBA$EFFECT$SPD.obl"
sed -i "s/Absorb/$EFFECT/g" "IBA$EFFECT$WLP.obl"
sed -i "s/Absorb/$EFFECT/g" "IBA$EFFECT$PRS.obl"
