#!/bin/zsh
WINEPREFIX=~/.obl winetricks isolate_home 
echo "Install sandboxed"
cd ~/.obl/drive_c/Oblivion/
WINEPREFIX=~/.obl wine obse_loader.exe -editor -notimeout
#wine obse_loader.exe -editor -notimeout
