#!/bin/zsh
cd "/home/kat/Scripts/" && zsh cse-no.sh # set game mode
cd /run/media/SSD/Oblivion-Stuff/Mopy/ &&  wine "Wrye Bash.exe" # WINEPREFIX="$HOME/.wine32"
#WINEPREFIX="$HOME/.wine32" wine python Z:/run/media/SSD/Oblivion-Stuff/wrye-zsh/Mopy/Wrye\ Bash\ Launcher.pyw -o Z:/run/media/SSD/SteamLibrary/steamapps/common/Oblivion


